# Generated by Django 4.2.8 on 2024-03-13 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registerapp', '0002_remove_userprofile_user_profile_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
