# Generated by Django 4.2.8 on 2024-03-13 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_movie_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='user',
            new_name='created_by',
        ),
    ]
