# Generated by Django 4.2.8 on 2024-03-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_rename_user_movie_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created_by',
        ),
    ]
