# Generated by Django 4.2.8 on 2024-03-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0008_category_movie_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
