# Generated by Django 4.2.8 on 2024-03-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0011_alter_movie_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(max_length=250),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
