# Generated by Django 4.2.8 on 2024-03-15 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0013_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('name',), 'verbose_name': 'movie', 'verbose_name_plural': 'movies'},
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieapp.category'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='desc',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(blank=True, upload_to='gallery'),
        ),
    ]
