# Generated by Django 4.2.8 on 2024-03-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0014_alter_movie_options_movie_slug_alter_movie_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
